//Program to demonstrate exception handling in c#.net.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ConsoleApplication14
{
    public class Program
    {
        public static void Main()
        {
            try
            {
                int a = 2;
                int b = 0;
                int c = a / b;
                Console.WriteLine(c);
            }
            catch (Exception e)
            {
                Console.WriteLine("Exception occurred:-" + e);
            }
            finally
            {
                Console.WriteLine("Exception handled");
            }
            Console.ReadLine();
        }
    }
}
